// -----------------------------------------------------------------------------
// b012_data — Full example entry point
//
// Each concern has its own self-contained, runnable file:
//
//   * `sqlite_example.dart` — SQLite CRUD demo (auto-generated by
//                             `DataAccess.instance` around the `Person` entity).
//   * `disc_example.dart`   — File system / binary file demo
//                             (`DiscData.instance` around the `Images` entity).
//
// This `main.dart` simply orchestrates both demos in sequence. Run a single
// one with `flutter run -t example/sqlite_example.dart` or
// `flutter run -t example/disc_example.dart`.
// -----------------------------------------------------------------------------

import 'package:flutter/material.dart';
import 'disc_example.dart' as disc;
import 'sqlite_example.dart' as sqlite;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1. SQLite CRUD walk-through (Person entity).
  await sqlite.runSqliteDemo();

  // 2. File system / binary file walk-through (Images entity).
  await disc.runDiscDemo();

  runApp(
    const MaterialApp(
      home: Scaffold(body: Center(child: Text('b012_data tests completed'))),
    ),
  );
}
