name: b012_data
description: b012_data is a package that allow you to build, generate and manipulate data (sqlfite and disc files) very easily
version: 1.0.2
homepage: https://birane012.github.io
repository: https://github.com/birane012/b012_data.git

#Supported platforms
platforms:
  android:
  ios:
  macos:
  windows:
  linux:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.2.1+1
  sqflite: ^2.2.5
  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1