name: b012_data
description: b012_data is a package that allow you to build, generate and manipulate data (sqlfite and disc files) very easily
version: 1.0.0
homepage: https://birane012.github.io
repository: https://github.com/birane012/b012_data.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.4+1
  path_provider: ^2.0.12


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: